// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartKasir.Infrastructure.Persistence;

#nullable enable

namespace SmartKasir.Infrastructure.Migrations;

[DbContext(typeof(SmartKasirDbContext))]
partial class SmartKasirDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("SmartKasir.Core.Entities.Category", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer");

            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)");

            b.HasKey("Id");
            b.HasIndex("Name").IsUnique();
            b.ToTable("Categories", (string?)null);
        });

        modelBuilder.Entity("SmartKasir.Core.Entities.Product", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<string>("Barcode")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("character varying(50)");

            b.Property<int>("CategoryId")
                .HasColumnType("integer");

            b.Property<bool>("IsActive")
                .ValueGeneratedOnAdd()
                .HasColumnType("boolean")
                .HasDefaultValue(true);

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)");

            b.Property<decimal>("Price")
                .HasPrecision(18, 2)
                .HasColumnType("numeric(18,2)");

            b.Property<int>("StockQty")
                .IsConcurrencyToken()
                .HasColumnType("integer");

            b.HasKey("Id");
            b.HasIndex("Barcode").IsUnique();
            b.HasIndex("CategoryId");
            b.ToTable("Products", (string?)null);
        });

        modelBuilder.Entity("SmartKasir.Core.Entities.Transaction", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<Guid>("CashierId")
                .HasColumnType("uuid");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("InvoiceNumber")
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnType("character varying(20)");

            b.Property<string>("PaymentMethod")
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnType("character varying(20)");

            b.Property<decimal>("TaxAmount")
                .HasPrecision(18, 2)
                .HasColumnType("numeric(18,2)");

            b.Property<decimal>("TotalAmount")
                .HasPrecision(18, 2)
                .HasColumnType("numeric(18,2)");

            b.HasKey("Id");
            b.HasIndex("CashierId");
            b.HasIndex("InvoiceNumber").IsUnique();
            b.ToTable("Transactions", (string?)null);
        });

        modelBuilder.Entity("SmartKasir.Core.Entities.TransactionItem", b =>
        {
            b.Property<long>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("bigint");

            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

            b.Property<decimal>("PriceAtMoment")
                .HasPrecision(18, 2)
                .HasColumnType("numeric(18,2)");

            b.Property<Guid>("ProductId")
                .HasColumnType("uuid");

            b.Property<int>("Quantity")
                .HasColumnType("integer");

            b.Property<decimal>("Subtotal")
                .HasPrecision(18, 2)
                .HasColumnType("numeric(18,2)");

            b.Property<Guid>("TransactionId")
                .HasColumnType("uuid");

            b.HasKey("Id");
            b.HasIndex("ProductId");
            b.HasIndex("TransactionId");
            b.ToTable("TransactionItems", (string?)null);
        });

        modelBuilder.Entity("SmartKasir.Core.Entities.User", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<bool>("IsActive")
                .ValueGeneratedOnAdd()
                .HasColumnType("boolean")
                .HasDefaultValue(true);

            b.Property<string>("PasswordHash")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)");

            b.Property<string>("Role")
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnType("character varying(20)");

            b.Property<string>("Username")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("character varying(50)");

            b.HasKey("Id");
            b.HasIndex("Username").IsUnique();
            b.ToTable("Users", (string?)null);
        });

        // Relationships
        modelBuilder.Entity("SmartKasir.Core.Entities.Product", b =>
        {
            b.HasOne("SmartKasir.Core.Entities.Category", "Category")
                .WithMany("Products")
                .HasForeignKey("CategoryId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.Navigation("Category");
        });

        modelBuilder.Entity("SmartKasir.Core.Entities.Transaction", b =>
        {
            b.HasOne("SmartKasir.Core.Entities.User", "Cashier")
                .WithMany()
                .HasForeignKey("CashierId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.Navigation("Cashier");
        });

        modelBuilder.Entity("SmartKasir.Core.Entities.TransactionItem", b =>
        {
            b.HasOne("SmartKasir.Core.Entities.Product", "Product")
                .WithMany()
                .HasForeignKey("ProductId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();

            b.HasOne("SmartKasir.Core.Entities.Transaction", "Transaction")
                .WithMany("Items")
                .HasForeignKey("TransactionId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Product");
            b.Navigation("Transaction");
        });

        modelBuilder.Entity("SmartKasir.Core.Entities.Category", b =>
        {
            b.Navigation("Products");
        });

        modelBuilder.Entity("SmartKasir.Core.Entities.Transaction", b =>
        {
            b.Navigation("Items");
        });
#pragma warning restore 612, 618
    }
}
